# Event classes and handlers
module Discordrb::Events
  # Event raised when any dispatch is received
  class RawEvent < Event
    # @return [Symbol] the type of this dispatch.
    attr_reader type: untyped

    alias t type

    # @return [Hash] the data of this dispatch.
    attr_reader data: untyped

    alias d data

    def initialize: (untyped `type`, untyped data, untyped `bot`) -> void
  end

  # Event handler for {RawEvent}
  class RawEventHandler < EventHandler
    def matches?: (untyped event) -> (false | untyped)
  end

  # Event raised when an unknown dispatch is received
  class UnknownEvent < RawEvent
  end

  # Event handler for {UnknownEvent}
  class UnknownEventHandler < RawEventHandler
  end
end
