version: 2.1

commands:
  setup-env:
    description: Sets up the testing environment
    steps:
      - run:
          name: Install OS packages
          command: apk add git build-base ruby-dev ruby-etc ruby-json libsodium
      - checkout
      - run:
          name: "Ruby version"
          command: |
            ruby -v
            echo $RUBY_VERSION > ruby_version.txt
      - restore_cache:
          keys:
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
          paths:
            - ./vendor/bundle

jobs:
  test_ruby_27:
    docker:
      - image: ruby:2.7-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

  test_ruby_30:
    docker:
      - image: ruby:3.0-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec


  test_ruby_31:
    docker:
      - image: ruby:3.1-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml

  rubocop:
    docker:
      - image: ruby:2.7-alpine
    steps:
      - setup-env
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  yard:
    docker:
      - image: ruby:2.7-alpine
    steps:
      - setup-env
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run YARD
          command: bundle exec yard --output-dir /tmp/workspace/docs
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docs

  pages:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install OS packages
          command: apk add git openssh-client-default
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Clone docs
          command: |
            mkdir -p ~/.ssh

            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >> ~/.ssh/known_hosts

            git clone $CIRCLE_REPOSITORY_URL -b gh-pages .
      - add_ssh_keys:
          fingerprints:
            - "9a:4c:50:94:23:46:81:74:41:97:87:04:4e:59:4b:4e"
      - run:
          name: Push updated docs
          command: |
            git config user.name "Circle CI"
            git config user.email "ci-build@shardlab.dev"

            SOURCE_BRANCH=$CIRCLE_BRANCH
            if [ -n "$CIRCLE_TAG" ]; then
              SOURCE_BRANCH=$CIRCLE_TAG
            fi

            mkdir -p $SOURCE_BRANCH
            rm -rf $SOURCE_BRANCH/*
            cp -r /tmp/workspace/docs/. ./$SOURCE_BRANCH/

            git add $SOURCE_BRANCH
            git commit --allow-empty -m "[skip ci] Deploy docs"
            git push -u origin gh-pages

workflows:
  test:
    jobs:
      - test_ruby_27
      - test_ruby_30
      - test_ruby_31
      - rubocop
      - yard
  deploy:
    jobs:
      - yard:
          filters:
            branches:
              only:
                - main
                - slash_commands
            tags:
              only: /^v.*/
      - pages:
          requires:
            - yard
          filters:
            branches:
              only:
                - main
                - slash_commands
            tags:
              only: /^v.*/
