version: 2.1

commands:
  setup-env:
    description: Sets up the testing environment
    steps:
      - run:
          name: Install OS packages
          command: apk add git build-base ruby-dev ruby-etc ruby-json libsodium
      - checkout
      - run:
          name: "Ruby version"
          command: |
            ruby -v
            echo $RUBY_VERSION > ruby_version.txt
      - restore_cache:
          keys:
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}
            - bundle-cache-v1-{{ checksum "ruby_version.txt" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-cache-v1-{{ checksum "ruby_version.txt" }}-{{ .Branch }}-{{ checksum "Gemfile" }}-{{ checksum "discordrb.gemspec" }}
          paths:
            - ./vendor/bundle

jobs:
  test_ruby_26:
    docker:
      - image: ruby:2.6-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec

  test_ruby_27:
    docker:
      - image: ruby:2.7-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec

  test_ruby_30:
    docker:
      - image: ruby:3.0-alpine
    steps:
      - setup-env
      - run:
          name: Run RSpec
          command: bundle exec rspec

  rubocop:
    docker:
      - image: ruby:2.6-alpine
    steps:
      - setup-env
      - run:
          name: Run Rubocop
          command: bundle exec rubocop -P

  yard:
    docker:
      - image: ruby:2.6-alpine
    steps:
      - setup-env
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run YARD
          command: bundle exec yard --output-dir /tmp/workspace/docs
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docs

  pages:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Clone docs
          command: git clone $CIRCLE_REPOSITORY_URL -b gh-pages .
      - add_ssh_keys:
          fingerprints:
            - "9a:4c:50:94:23:46:81:74:41:97:87:04:4e:59:4b:4e"
      - run:
          name: Push updated docs
          command: |
            git config user.name "Circle CI"
            git config user.email "ci-build@shardlab.dev"

            SOURCE_BRANCH=$CIRCLE_BRANCH
            if [ -n "$CIRCLE_TAG" ]; then
              SOURCE_BRANCH=$CIRCLE_TAG
            fi

            mkdir -p $SOURCE_BRANCH
            rm -rf $SOURCE_BRANCH/*
            cp -r /tmp/workspace/docs/. ./$SOURCE_BRANCH/

            git add $SOURCE_BRANCH
            git commit --allow-empty -m "[skip ci] Deploy docs"
            git push -u origin gh-pages

workflows:
  test:
    jobs:
      - test_ruby_26
      - test_ruby_27
      - test_ruby_30
      - rubocop
      - yard
  deploy:
    jobs:
      - yard:
          filters:
            branches:
              only:
                - main
                - slash_commands
            tags:
              only: /^v.*/
      - pages:
          requires:
            - yard
          filters:
            branches:
              only:
                - main
                - slash_commands
            tags:
              only: /^v.*/
