# frozen_string_literal: true

# Voice websocket opcodes
# @!visibility private
module Discordrb::Voice::Opcodes
  IDENTIFY = 0
  SELECT_PROTOCOL = 1
  READY = 2
  HEARTBEAT = 3
  SESSION_DESCRIPTION = 4
  SPEAKING = 5
  HEARTBEAT_ACK = 6
  RESUME = 7
  HELLO = 8
  RESUMED = 9
  CLIENT_CONNECT = 10
  CLIENT_DISCONNECT = 11
  DAVE_PREPARE_TRANSITION = 21
  DAVE_EXECUTE_TRANSITION = 22
  DAVE_TRANSITION_READY = 23
  DAVE_PREPARE_EPOCH = 24
  DAVE_MLS_EXTERNAL_SENDER = 25
  DAVE_MLS_KEY_PACKAGE = 26
  DAVE_MLS_PROPOSALS = 27
  DAVE_MLS_COMMIT_WELCOME = 28
  DAVE_MLS_ANNOUNCE_COMMIT_TRANSITION = 29
  DAVE_MLS_WELCOME = 30
  DAVE_MLS_INVALID_COMMIT_WELCOME = 31
end
